TemplateURL: BUCKET_URL_PLACEHOLDER/parallelcluster-ui.yaml
Parameters:
  - ParameterKey: Version
    ParameterValue: 3.4.0
  - ParameterKey: InfrastructureBucket
    ParameterValue: BUCKET_URL_PLACEHOLDER
  - ParameterKey: UserPoolId
    UsePreviousValue: true
  - ParameterKey: UserPoolAuthDomain
    UsePreviousValue: true
  - ParameterKey: SNSRole
    UsePreviousValue: true
  - ParameterKey: PublicEcrImageUri
    ParameterValue: public.ecr.aws/pcm/pcluster-manager-awslambda:latest
Capabilities:
  - CAPABILITY_AUTO_EXPAND
  - CAPABILITY_NAMED_IAM
DisableRollback: false
