Region: eu-west-1
Image:
  Os: alinux2
HeadNode:
  InstanceType: t3.xlarge
  Networking:
    SubnetId: subnet-03ffbdaeee8264db7
    AdditionalSecurityGroups:
      - sg-0fec342c8a6f2a5ea
  Ssh:
    KeyName: aws_rsa
  Iam:
    S3Access:
      - BucketName: cluster-accounting-demo
        EnableWriteAccess: true
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
      - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  CustomActions:
    OnNodeConfigured:
      Script: s3://cluster-accounting-demo/post-install.sh
      Args:
        - "s3://cluster-accounting-demo"
        - "arn:aws:secretsmanager:eu-west-1:628437107155:secret:DbPasswdSecret-pcluster-accounting-demo-ypp2xt"
        - "slurmdb-rds-instance.co8kwqpvly1t.eu-west-1.rds.amazonaws.com"
        - "3306"
Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: queue1
    ComputeResources:
    - Name: t2micro
      InstanceType: t2.micro
      MinCount: 0
      MaxCount: 10
    Networking:
      SubnetIds:
      - subnet-03ffbdaeee8264db7
