name: e2e
on: workflow_dispatch
jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
      working-directory: e2e
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: e2e
    - name: Run Playwright tests
      run: npm run e2e:test
      working-directory: e2e
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: e2e/test-results/
        retention-days: 30