name: e2e

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: eu-west-1
        role-to-assume: arn:aws:iam::063695377715:role/pcluster-manager-github-E2ETestExecution-Z7IMRUIJAZAO

    - name: Retrieve test user email and password
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-ids: |
          e2e/test1
        parse-json-secrets: true
      
    - name: Install dependencies
      run: npm ci
      working-directory: e2e
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: e2e
    - name: Run Playwright tests
      run: npm run e2e:test
      working-directory: e2e
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: e2e/test-results/
        retention-days: 30